name: Velopack Build & Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag version (e.g. v1.0.9)'
        required: true

jobs:
  build-and-package:
    runs-on: windows-latest

    env:
      PACK_ID: Launcher-Velopack-Tests
      MAIN_EXE: main.exe  # << Replace with your actual entry exe
      BUILD_DIR: build
      RELEASE_DIR: build/release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Build the app
        run: |
          mkdir $env:BUILD_DIR
          cd $env:BUILD_DIR
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Download and unzip Velopack CLI (Windows .zip)
        run: |
          curl -L -o vpk.zip https://github.com/velopack/velopack/archive/refs/tags/0.0.1335-g2ad2c37.zip
          Expand-Archive -Path vpk.zip -DestinationPath vpk
        shell: pwsh

      - name: Run Velopack Pack
        run: |
          & "./vpk/vpk.exe" pack `
            --packId $env:PACK_ID `
            --packVersion v1.0.9 `
            --packDir "$env:BUILD_DIR/Release" `
            --mainExe $env:MAIN_EXE `
            --outputDir $env:RELEASE_DIR
        shell: pwsh

      - name: Upload .vpk to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          files: |
            ${{ env.RELEASE_DIR }}/*.vpk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
