name: Velopack Build & Release

on:
  push:
    tags:
      - "*"

jobs:
  build-and-package:
    runs-on: windows-latest

    env:
      PACK_ID: Launcher-Velopack-Tests
      MAIN_EXE: main.exe
      BUILD_DIR: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Build the app
        run: |
          mkdir $env:BUILD_DIR
          cd $env:BUILD_DIR
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
        shell: pwsh

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Install Velopack CLI as global tool
        run: dotnet tool install -g vpk
        shell: pwsh

      - name: Add .NET tools to PATH
        run: echo "${{ env.HOME }}\.dotnet\tools" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Run Velopack Pack
        shell: pwsh
        run: |
          vpk pack `
            --packId "$env:PACK_ID" `
            --packVersion "${{ github.ref_name }}" `
            --packDir "$env:BUILD_DIR/Release" `
            --mainExe "$env:MAIN_EXE" `

      - name: Upload .vpk to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ env.RELEASE_DIR }}/*.vpk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to gh-pages branch
        shell: pwsh
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          cd gh-pages

          Remove-Item * -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item ../Releases/* -Destination . -Recurse -Force

          git add .
          git commit -m "Update gh-pages with release ${{ github.ref_name }}"
          git push origin HEAD:gh-pages --force