name: Velopack Build & Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag of the release'
        required: true
  release:
    types: [published]

jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
      - name: Set release tag (manual or event)
        run: echo "RELEASE_TAG=${{ github.event.release.tag_name || inputs.tag_name }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Build the app
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Download Velopack CLI
        run: |
          curl -L -o vpk.exe https://github.com/velopack/velopack/releases/latest/download/vpk-windows-x64.exe
        shell: bash

      - name: Run Velopack Pack
        run: |
          ./vpk.exe pack --platform win-x64 --output-dir ./build/release
        shell: bash

      - name: Upload .vpk to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: build/release/*.vpk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
