name: Velopack Build & Release

on:
  release:
    types: [published]

jobs:
  build-and-package:
    runs-on: windows-latest

    env:
      PACK_ID: Launcher-Velopack-Tests
      MAIN_EXE: main.exe
      BUILD_DIR: build
      RELEASE_DIR: build/release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Build the app
        run: |
          mkdir $env:BUILD_DIR
          cd $env:BUILD_DIR
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
        shell: pwsh

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Install Velopack CLI as global tool
        run: dotnet tool install -g vpk
        shell: pwsh

      - name: Add .NET tools to PATH
        run: echo "${{ env.HOME }}\.dotnet\tools" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Run Velopack Pack
        run: |
          vpk pack `
            --packId $env:PACK_ID `
            --packVersion ${{ steps.version.outputs.version }} `
            --packDir "$env:BUILD_DIR/Release" `
            --mainExe $env:MAIN_EXE `
            --outputDir $env:RELEASE_DIR
        shell: pwsh

      - name: Upload .vpk to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ${{ env.RELEASE_DIR }}/*.vpk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
